services:
  frontend:
    image: tz-frontend
    build:
      context: .
      dockerfile: config/docker.frontend
    ports:
      - "3000:3000"
    command: npm run preview -- --host --port 3000
    environment:
      - backend_url=http://backend:5000
      - frontend_url=http://frontend:3000

  backend:
    image: tz-backend
    build:
      context: .
      dockerfile: config/docker.backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
      - /app/node_modules
    command: npm run start:backend
